apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: devops
image: rancher/k3s:v1.36.2-k3s1
servers: 1
agents: 4
network: k3dnet
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "180s"
  k3s:
    extraArgs:
      - arg: --tls-san=k3d-devops-serverlb
        nodeFilters:
          - server:*
