{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "quote-api.fullname" . }}
  labels:
    {{- include "quote-api.labels" . | nindent 4 }}
    release: {{ .Values.monitoring.releaseLabel }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "quote-api.name" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
{{- end }}
